flowchart TB
  subgraph CAP_001["CAP-001: Browse products"]
  end
  subgraph CAP_002["CAP-002: Quote a car policy"]
    CAP_002__PROC_001["PROC-001: Calculate a car premium"]
    CAP_002__PROC_002["PROC-002: Buy a car policy"]
  end
